name = "The Gangs Modpack"
author = "moelotusdead6-spec"
version = "0.1.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e56b4492867faa40d9d78bb3f83f8e59f1103413d06eb6e9602f15c96e7423f7"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
