name = "The Gangs Modpack"
author = "moelotusdead6-spec"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa895b6cd6aa49d61d7825ed6a00b8a899d4c0e980a173a657594c54474a4954"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
