config_version = 3
enable_system_global_packs = false
log_pack_ids = false

[resourcepacks]
required = [
    "resourcepacks/",
    "global_packs/required_resources/"
]
enable_builtin = []

[datapacks]
required = [
    "datapacks/",
    "resourcepacks/",
    "global_packs/required_data/"
]
optional = [
    "global_packs/optional_data/"
]
enable_builtin = []
